/*! Bespoke.js v0.3.1 © 2013 Mark Dalgleish, Licensed MIT */
!function(n,e){var t=function(n,e){var t=n.blur?n:document.querySelector(n),a=[].slice.call(t.children,0),o=a[0],u={},d=function(n,e){a[n]&&(p("deactivate",m(o,e)),o=a[n],a.map(s),p("activate",m(o,e)),r(o,"active"),c(o,"inactive"))},s=function(n,e){var t=e-a.indexOf(o),i=t>0?"after":"before";["before(-\\d+)?","after(-\\d+)?","active","inactive"].map(c.bind(0,n)),n!=o&&["inactive",i,i+"-"+Math.abs(t)].map(r.bind(0,n))},h=function(n,e){p("slide",m(a[n],e))&&d(n,e)},l=function(n,e){var t=a.indexOf(o)+n;p(n>0?"next":"prev",m(o,e))&&d(t,e)},v=function(n,e){return(u[n]||(u[n]=[])).push(e),function(){u[n]=u[n].filter(function(n){return n!=e})}},p=function(n,e){return(u[n]||[]).reduce(function(n,t){return n&&t(e)!==!1},!0)},m=function(n,e){return e=e||{},e.index=a.indexOf(n),e.slide=n,e},x={on:v,fire:p,slide:h,next:l.bind(0,1),prev:l.bind(0,-1),parent:t,slides:a};r(t,"parent"),a.map(function(n){r(n,"slide")});for(var b in e)f[b](x,e[b]);return d(0),i.push(x),x},i=[],r=function(e,t){e.classList.add(n+"-"+t)},c=function(e,t){e.className=e.className.replace(RegExp(n+"-"+t+"(\\s|$)","g")," ").trim()},a=function(n){return function(e){i.map(function(t){t[n](e)})}},o=function(n){return{from:function(e,i){return(i=i||{})[n]=!0,t(e,i)}}},u=function(n){return function(e){var t,i;document.addEventListener("keydown",function(t){(34==t.which||32==t.which||"X"==n&&39==t.which||"Y"==n&&40==t.which)&&e.next(),(33==t.which||"X"==n&&37==t.which||"Y"==n&&38==t.which)&&e.prev()}),e.parent.addEventListener("touchstart",function(e){1==e.touches.length&&(t=e.touches[0]["page"+n],i=0)}),e.parent.addEventListener("touchmove",function(e){1==e.touches.length&&(e.preventDefault(),i=e.touches[0]["page"+n]-t)}),e.parent.addEventListener("touchend",function(){Math.abs(i)>50&&(i>0?e.prev():e.next())})}},f={horizontal:u("X"),vertical:u("Y")};e[n]={from:t,slide:a("slide"),next:a("next"),prev:a("prev"),horizontal:o("horizontal"),vertical:o("vertical"),plugins:f}}("bespoke",window);
/*! bespoke-hash v0.1.2 © 2013 Mark Dalgleish, Licensed MIT */
(function(e){e.plugins.hash=function(e){var t,n=function(){var t=window.location.hash.slice(1),n=parseInt(t,10);t&&(n?r(n-1):e.slides.forEach(function(e,n){e.getAttribute("data-bespoke-hash")===t&&r(n)}))},r=function(n){n!==t&&e.slide(n)};setTimeout(function(){n(),e.on("activate",function(e){var n=e.slide.getAttribute("data-bespoke-hash");window.location.hash=n||e.index+1,t=e.index}),window.addEventListener("hashchange",n)},0)}})(bespoke);
/*! bespoke-state v0.2.2 © 2013 Mark Dalgleish, Licensed MIT */
(function(e){e.plugins.state=function(e){var t=function(t,n){var r=n.slide.getAttribute("data-bespoke-state");r&&r.split(" ").forEach(function(n){n&&e.parent.classList[t](n)})};e.on("activate",t.bind(null,"add")),e.on("deactivate",t.bind(null,"remove"))}})(bespoke);
/*! bespoke-touch v0.1.0 © 2013 Mark Dalgleish, Licensed MIT */
bespoke.plugins.touch=function(a,b){var c,d,e=b===!0||"horizontal"==b?"X":"Y";a.parent.addEventListener("touchstart",function(a){1==a.touches.length&&(c=a.touches[0]["page"+e],d=0)}),a.parent.addEventListener("touchmove",function(a){1==a.touches.length&&(a.preventDefault(),d=a.touches[0]["page"+e]-c)}),a.parent.addEventListener("touchend",function(){Math.abs(d)>50&&(d>0?a.prev():a.next())})};

var ready=function(){function e(){if(!a.isReady){try{document.documentElement.doScroll("left")}catch(t){return void setTimeout(e,1)}a.ready()}}function t(e){a.bindReady();a.type(e);n.done(e)}var n,o,r={};r["[object Boolean]"]="boolean",r["[object Number]"]="number",r["[object String]"]="string",r["[object Function]"]="function",r["[object Array]"]="array",r["[object Date]"]="date",r["[object RegExp]"]="regexp",r["[object Object]"]="object";var a={isReady:!1,readyWait:1,holdReady:function(e){e?a.readyWait++:a.ready(!0)},ready:function(e){if(e===!0&&!--a.readyWait||e!==!0&&!a.isReady){if(!document.body)return setTimeout(a.ready,1);if(a.isReady=!0,e!==!0&&--a.readyWait>0)return;n.resolveWith(document,[a])}},bindReady:function(){if(!n){if(n=a._Deferred(),"complete"===document.readyState)return setTimeout(a.ready,1);if(document.addEventListener)document.addEventListener("DOMContentLoaded",o,!1),window.addEventListener("load",a.ready,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",o),window.attachEvent("onload",a.ready);var t=!1;try{t=null==window.frameElement}catch(r){}document.documentElement.doScroll&&t&&e()}}},_Deferred:function(){var e,t,n,o=[],r={done:function(){if(!n){var t,d,i,c,u,y=arguments;for(e&&(u=e,e=0),t=0,d=y.length;d>t;t++)i=y[t],c=a.type(i),"array"===c?r.done.apply(r,i):"function"===c&&o.push(i);u&&r.resolveWith(u[0],u[1])}return this},resolveWith:function(r,a){if(!n&&!e&&!t){a=a||[],t=1;try{for(;o[0];)o.shift().apply(r,a)}finally{e=[r,a],t=0}}return this},resolve:function(){return r.resolveWith(this,arguments),this},isResolved:function(){return!(!t&&!e)},cancel:function(){return n=1,o=[],this}};return r},type:function(e){return null==e?String(e):r[Object.prototype.toString.call(e)]||"object"}};return document.addEventListener?o=function(){document.removeEventListener("DOMContentLoaded",o,!1),a.ready()}:document.attachEvent&&(o=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",o),a.ready())}),t}();

ready(function(){if(document.getElementById('launched-placeholder'))loadPresentation();if (!window.presStarted){bespoke.horizontal.from('article', {hash: true,state: true,touch: true });}});

